# Generated by Django 5.1.6 on 2025-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='has_garrison',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Garrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garrison_name', models.CharField(max_length=100)),
                ('dish', models.ManyToManyField(related_name='garrisons', to='dishesAPI.dish')),
            ],
        ),
    ]
