# Generated by Django 5.1.6 on 2025-02-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(through='dishesAPI.OrderDish', to='dishesAPI.dish'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
