# Generated by Django 5.1.6 on 2025-02-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesAPI', '0002_order_dishes_alter_orderdish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(null=True, through='dishesAPI.OrderDish', to='dishesAPI.dish'),
        ),
    ]
