# Generated by Django 5.1.6 on 2025-04-06 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesAPI', '0002_dish_has_garrison_garrison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishesAPI.order')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishesAPI.dish')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishesAPI.invoice')),
            ],
        ),
    ]
