# Generated by Django 5.1.6 on 2025-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesAPI', '0004_alter_order_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
        migrations.AddField(
            model_name='order',
            name='order_dish',
            field=models.ManyToManyField(through='dishesAPI.OrderDish', to='dishesAPI.dish'),
        ),
    ]
