# Generated by Django 5.1.6 on 2025-02-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesAPI', '0005_remove_order_dishes_order_order_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='embebedAR',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
