# Generated by Django 5.1.6 on 2025-03-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishesAPI', '0006_dish_embebedar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='embebedAR',
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(),
        ),
    ]
